### ISSUE TITLE
Does not open todo.txt on WebDAV server 

### ISSUE THREAD

**Issue by uGeek** [tmaegel/ntodotxt#12]
When I log in to the path of my todo.txt file, it does not open the file. The screen stays white

**Comment by lommes** [comment]
Same for me.  

logcat seems to throw this error https://github.com/tmaegel/ntodotxt/blob/13801cce4fb899d0bec81039a13a7fb9e8812b00/lib/data/todo/todo_list_api.dart#L214

```
01-20 10:02:45.470 27723 28259 I flutter : INFO: 2024-01-20 10:02:45.470018: Use local+webdav backend
01-20 10:02:45.471 27723 28259 I flutter : FormatException: Invalid server foramt.
```

**Comment by tmaegel** [comment]
Should also fixed. See #17
