### ISSUE TITLE
Local file location

### ISSUE THREAD

**Issue by breadcat** [tmaegel/ntodotxt#16]
I'm running version 0.4.3 on Android currently, when first launched I selected local file storage as I didn't have a WebDAV server available.

I've set one up now and would like to move my existing file onto this server and start syncing remotely but I can't find the file. I've had a quick look through the source and see references to `data.db` and `todo.txt` but can't find either of these files when checking my phones filesystem.

Can you let me know where this file is stored? Apologies if this is a dumb question.

**Comment by tmaegel** [comment]
At the moment, the app stores the data (todo.txt) in the app's cache directory (/data/data/<application-path>/cache/). I am still planning to make the path configurable (Issue #7).

Alternatively, you can also log out in the settings (reconfigure the connection - Offline or WebDav).

**Comment by breadcat** [comment]
Ah, that's why I won't be able to find it, I'm accessing the phones storage [using FTP](https://github.com/wolpi/prim-ftpd), my USB port is out of order so I think I might need to start the list again. No worries, thanks for your reply and your work on this.
