### ISSUE TITLE
Missing server port.

### ISSUE THREAD

**Issue by HumanMus1c** [tmaegel/ntodotxt#17]
I'm using Koofr and infiniCLOUD webdav servers which don't has specific server port.
![Screenshot_20240131_190654_de tnmgl ntodotxt](https://github.com/tmaegel/ntodotxt/assets/46023154/dcd57622-5824-41b5-8a7f-018b91f1b745)

**Comment by lommes** [comment]
Due to the regex pattern you have to specify the server port in any case.

In your case this would be 443, so https://app.koofr.net:443/dav/...

You will, most likely, end up with #16 after using this
