### ISSUE TITLE
Hamburger menu hidden when coming back from new task view

### ISSUE THREAD

**Issue by jackrgm** [tmaegel/ntodotxt#18]
When a new task with filled fields get cancelled, pressing the back button, the task list screen no longer shows the hamburger menu icon, and the 'Todos' title is shifted to where it was.

To reproduce:

* Open app, note the menu icon in the top left beside 'Todos'.
* Create new task. Enter a task name.
* Hit the back button.
* Note the menu icon is gone.

Hope this helps.

**Comment by jackrgm** [comment]
I just realised the same happens even when I save the new task. Updated issue title.

**Comment by tmaegel** [comment]
Thank you for your reporting. The issue was solved by [c181ab6](https://github.com/tmaegel/ntodotxt/commit/c181ab6fe661592eff357b68167e365df07939c6).
