### ISSUE TITLE
erorr: Failed to create the file /todo.txt

### ISSUE THREAD

**Issue by evergreen-tm** [tmaegel/ntodotxt#20]
hi!
I found ntodotxt via f-droid and I love both the concept and the execution.
I am on the latest version, 0.4.6, from the github release.
I login to my nextcloud server (hosted as a TrueNAS Scale app) via webdav with my url (like https://nc.myurl.xyz:443), with a path of /remote.php/dav/files, and then the login info for the account.
This sends me to the main screen where I see the recurring error "Failed to create the file /todo.txt"

I am able to send PUT requests via curl to create and modify files via the same webdav link. I will do further work tonight to determine if this is a Nextcloud problem, but if you see something obvious that I don't, or are able to point me in the right direction for places to look, please let me know.

**Comment by tmaegel** [comment]
Thank you for reporting the issue.

The integration tests ran on the desktop version only. As a result, I did not notice the missing permission `android.permission.INTERNET`.

I fixed this in the next release `v0.4.7`.
