### ISSUE TITLE
WebDAV: Support subfolders and multiple todo.txt

### ISSUE THREAD

**Issue by webracer999** [tmaegel/ntodotxt#29]
Hi,

is there a chance to select a todo.txt from a WebDAV subfolder?
Or even to select different todo.txt? -> I have two todo.txt - one for my normal tasks and one as a shopping list (`shoppinglist.txt`).

BTW, great project - thank you for your work!

**Comment by tmaegel** [comment]
Thank you for your feedback.

To customize the remote todo.txt path and filename is already on my roadmap.
But do manage multiple todo.txt files at the same time is not my focus for this app.

**Comment by webracer999** [comment]
For me, managing multiple todo.txt files simultaneously isn't necessary. A "simple" option to switch between multiple files would suffice. :slightly_smiling_face:  Until now, I've been using https://github.com/mpcjanssen/simpletask-android, but it was recently archived, prompting me to look for a new alternative.

However, if this feature isn't a priority for you, that's perfectly fine. After all, you have the final say on your project's direction! :slightly_smiling_face:

**Comment by tmaegel** [comment]
With version `v0.10.0` it is now possible to save todos in folders and subfolders. An option to quickly switch between several todo files  is not a planned feature. You may be able to cover your use case with different context and project tags.
