### ISSUE TITLE
Permission error 13 when opening pre-existing folder. 

### ISSUE THREAD

**Issue by juleskers** [tmaegel/ntodotxt#30]
Hi! I'm evaluating several todo.txt apps, and ntodo is a promising candidate.

I ran into a hang condition *immediately* at first start.

After installing, I chose "offline". Then I tapped the  path, and navigated to my pre-existing shared folder.
This resulted in a blank, grey screen with no way to proceed. 

My guess is that the app chokes on some other, preexisting files in the folder. My shared folder (managed by Sync Thing) also contains an encrypted MyExpenses database, so it has subfolders and some textfiles with "gibberish".

It did not make a difference if a `todo.txt` exists in the folder root or not. The gray screen happens both with and without that file. 

The only way out of the gray screen I've found is to uninstall the app, clear the cache from device settings, and then re-install, which is *really* elaborate. 

# screenshots
The offline-login screen
![Screenshot_20240306-152222_ntodotxt](https://github.com/tmaegel/ntodotxt/assets/7068025/7015efad-ee69-4eea-92c8-9c5de5cbe374)

The "evil" folder, containing a MyExpenses DB + todo.txt
![Screenshot_20240306-152331_Bestanden](https://github.com/tmaegel/ntodotxt/assets/7068025/94655dd4-704b-47bb-9c39-e0f732ff962e)

Resulting hang: gray screen  
![Screenshot_20240306-152342_ntodotxt](https://github.com/tmaegel/ntodotxt/assets/7068025/964935dc-9731-4800-8592-5aa6f59aa49e)

**Comment by tmaegel** [comment]
Thank you for reporting this issue.
Which version you are using? The issue should not fix with version 0.6.0. However, a precise error description should be displayed.

Normally the file picker should ask you for authorization for the folder. I assume this does not happen because the folder already exists and was not created.

I check this and make sure that the authorization is also correct for existing folders.

**Comment by tmaegel** [comment]
I have checked this. With version 0.6.0 you should receive an error message if the permissions of the folder does not match. However, the real problem remains.

**Comment by juleskers** [comment]
Ah, I am on 0.5.1, fresh from F-droid, I should have mentioned that 😅 

Tapping the local path does indeed get me the (system) filepicker, and "deze map gebruiken" (Dutch, "use this folder") does indeed get a system-pop-up asking for permission, which I granted. 

Is v0.6.0 something you just created? Or can I get it somewhere?

**Comment by tmaegel** [comment]
> Is v0.6.0 something you just created? Or can I get it somewhere?

Version 0.6.0 should be in the fdroid-store since today.

**Comment by juleskers** [comment]
Aha, I needed to refresh my F-droid source lists, now they see 0.6.0.

The error is indeed a permissions problem:
OS error: permission denied;error 13.

I did grant the requested "storage access" permission when first-tapping the path. 

I wonder if this is due to my usage of android 12. That, I believe, has an additional finer grained, per-folder system, which may be infering.  
Alternatively, it could be that that folder is already "claimed" by the MyExpenses app, though I am not an Android permission expert.. 


![Screenshot_20240306-162002_ntodotxt](https://github.com/tmaegel/ntodotxt/assets/7068025/a3e015e4-0ff4-4bf4-b4cd-a7e41e8907b0)

**Comment by juleskers** [comment]
P.S. I want to stress again that I mean my feedback in the most positive way!

Getting anything at all working on Android is non-trivial, so, thanks for making this, making it in the open, and making it in a privacy friendly way without tracking ❤️

**Comment by kiddae** [comment]
The issue still does not seem to have been fixed (exactly the same problem running v0.6.1 from F-Droid).

**Comment by juleskers** [comment]
Positive feedback: Last night I received the update that fixed this. I can now open existing todos 🎉

It seems the app now requires the "manage all files" permission to solve this? Regardless, Android asked me if I wanted to grant permission to the specific folder as well.

**Comment by tmaegel** [comment]
> It seems the app now requires the "manage all files" permission to solve this? Regardless, Android asked me if I wanted to grant permission to the specific folder as well.

Yes, because I don't restrict the path where the todos may be saved and for accessing the Android's file system the app needs the MANAGE_EXTERNAL_STORAGE permission (Permission.manageExternalStorage - "manage all files").

The dialog that asks for permission for a specific folder comes from the [file_picker](https://pub.dev/documentation/file_picker/latest/) plugin. The dialog is not really necessary, but I don't see any way to turn it off either.
