### ISSUE TITLE
Offline login screen: did not know how to proceed

### ISSUE THREAD

**Issue by juleskers** [tmaegel/ntodotxt#31]
Hi! As I just wrote in #30, I'm trying out ntdotxt. 

First, I should give kudos for adding the offline functionality. It's great to see a cloud-free alternative mode, and it is so nice to see how it perfectly integrates with my existing SyncThing setup. 

After installing, I was uncertain how to proceed on the "offline login" screen. 

The only Ui-elements are:
1. The text "login - offline" (huh? Log in to what?) 
2. A cryptic "local path" mentioning "cache" (aren't caches supposed to be deleted without consequences? 
3. A blue "login" button (log in to what? You can't log in to your own file system, can you?) 

I ended up *guessing* that tapping the path would do something, and it gave me an option to choose a local folder.  
That's okay, but not great user flow. 

I'd recommend:
- renaming the "login - offline" title to something like "choose storage folder" 
- giving the user a clear instruction what they're supposed to do, e.g. "choose a folder by tapping the current local path" 
- adding a description to "local path", something like "folder where ntodo will save its todo.txt file" 
- renaming the "login" button to "proceed" or "OK" or some other equivalent that makes sense for "offline". 
- given that I use it with SyncThing, I am not sure how correct the description "offline" is. Perhaps other synonyms will give more indication to the "externally synced" capability. It's such a killer feature that it deserves more attention in my humble opinion ❤️ 

# screenshots
The offline-login screen
![Screenshot_20240306-152222_ntodotxt](https://github.com/tmaegel/ntodotxt/assets/7068025/7015efad-ee69-4eea-92c8-9c5de5cbe374)

**Comment by tmaegel** [comment]
Thank you for your feedback.

You mentioned really good points. I agree that "offline" is not the appropriate term.

**Comment by juleskers** [comment]
You're welcome, and **thank ypu** for making this app in a open source, privacy-friendly manner!

I've been thinking about possible synonyms, and one keeps coming back to me, borrowed from the simpletask app: "cloud-free".
I think "local / cloud-free" would make a good short description/title.
Alternatively: "local / externally synced".

In both cases, the "select folder" screen could have an explanation along the lines of: 
> Use this option if you don't need synchronisation across multiple devices, or if you have an external app that takes care of syncing the folder (e.g. Sync Thing, NextCloud, etc)

Although, perhaps that explanation should be available *before* you chose the option, that is, on the "offline vs webdav" screen.
