### ISSUE TITLE
Different Priority styles

### ISSUE THREAD

**Issue by inson1** [tmaegel/ntodotxt#32]
A, B, C, D, E, F, none priority doesnt look good to me, so what if we could choose style?

A, B, C, D, E, F, None
1, 2, 3, 4, 5, 6, None
Urgent, High, Higher, Medium, Lower, Low, None (idk about higher and lower, maybe something else)

**Comment by tmaegel** [comment]
> The priority is an uppercase character from A-Z enclosed in parentheses and followed by a space.

This app based on the [todo.txt](https://github.com/todotxt/todo.txt?tab=readme-ov-file#rule-1-if-priority-exists-it-always-appears-first) format.
