### ISSUE TITLE
Feature Request: Don't add `id:xxxxxxxxx` to items in the `todo.txt` file itself

### ISSUE THREAD

**Issue by David-Else** [tmaegel/ntodotxt#34]
I would like to share the `todo.txt` file on my server with multiple bits of software on multiple platforms, not just android, but `ntodotxt` adds proprietary metadata in the form of an id to each item in the list. While this does not break the other software I am happening to use, it is not a part of the official rules https://github.com/todotxt/todo.txt and does spoil the appearance in other software.

I am not sure of the best solution, but I assume it would not be too hard to create some kind of hash table lookup to avoid injecting the id into the text itself? Maybe an ID is not needed or could just be generated in memory when editing? In the Helix editor with VS Code theme the id looks like this when using the output of `ntodotxt`:

![image](https://github.com/tmaegel/ntodotxt/assets/12832280/e370ee81-5535-4aaf-b4c3-1d93a1c08cff)

With a big file the clutter really adds up.

Cheers, thanks again for this great sw.

**Comment by tmaegel** [comment]
Thank you for your feedback. I totally agree with your feedback.

The `id` is an artefact of the early days of the app development and was simply a quick and dirty implementation to make sure that each todo on remote side compares only with the correct todo on the local device (synchronisation).

I'm already planning to get rid of the `id`.

**Comment by mshuflin** [comment]
I am excited about using ntodo, and especially since simpletask is archived now, I want to make the move to ntodo, this id is probably the last thing holding me back from transitioning. So much great work on making a good looking app! Thank you!

**Comment by tmaegel** [comment]
With version `v0.9.0`, ids are no longer automatically appended to the todos in `todo.txt`. Please note, however, that existing ids are not automatically removed. You have to be remove these once by manually editing them in your `todo.txt` or use the app to remove the ids.
