### ISSUE TITLE
Make todo.txt filename customizable

### ISSUE THREAD

**Issue by ludrol** [tmaegel/ntodotxt#35]
Obsidian can't use .txt files, so there is an add-on that uses .todotxt extension.

**Comment by ludrol** [comment]
@tmaegel Can you add filename.todotxt support instead of only todo.txt?

**Comment by tmaegel** [comment]
Okay, I understand. Yes, that should be possible, as I also plan to make the file name `todo.txt` customizable.

**Comment by tmaegel** [comment]
You can define custom remote paths and todo filename with the next release `v0.10.0`. Custom local path and todo filename is already possible.
