### ISSUE TITLE
Android app uses incorrect keyboard configuration, blocking swipe typing and word suggestions

### ISSUE THREAD

**Issue by source6212** [tmaegel/ntodotxt#36]
Hello!

I've been really enjoying this app, but I think there is a misconfiguration with the keyboard somewhere. When typing in the search and the task title boxes, my keyboard functions the way it would when entering my lock screen password. 

It goes incognito, swipe to type is disabled, auto-capitalization is disabled, next word suggestions don't appear, etc. 

I can open a PR once I find where it's configured, it should be a pretty simple fix.

Thank you!

**Comment by tmaegel** [comment]
I will check this out.

**Comment by tmaegel** [comment]
This should be solved with the next release.
