### ISSUE TITLE
problem with WebDAV 

### ISSUE THREAD

**Issue by matzefrey** [tmaegel/ntodotxt#46]
I just found todo.txt and this app and would like to try it out. Unfortunately, I can't manage to start the WebDAV access. Maybe I'm just blind and missing a trivial point, and maybe someone can help me? 

This is my university's cloud, but it is based on Nextcloud. I get the following address as WebDAV access: 

'https://tu-dortmund.sciebo.de/remote.php/dav/files/firstname.surname%40tu-dortmund.de/'  

I did the following: 

* **Server:** https://tu-dortmund.sciebo.de:443
* **Base URL:** /remote.php/dav/files/firstname.surname%40tu-dortmund.de/
* **Username:** firstname.surname@tu-dortmund.de 
* **Password:** my password

Maybe the problem is the '%40' in the URL and my Username with the '@'? 

Many thanks in advance.

**Comment by tmaegel** [comment]
Thank you for your feedback.

This is not really an issue. You have two options:
A) Do not add the username to the base url: `/remote.php/dav/files/`
or
B) Add the username in the correct form to the base url: `/remote.php/dav/files/firstname.surname@tu-dortmund.de/`

The url encoding happens automatically. It is not necessary to do this yourself beforehand.
