### ISSUE TITLE
when editing do not include context in title

### ISSUE THREAD

**Issue by georgepapas123** [tmaegel/ntodotxt#57]
in Edit screen, it may be better to omit contexts from the title, this way if the user wants to edit the title they don't have to navigate before the @xxxxxx to do so (contexts are listed under contexts anyway).

**Comment by tmaegel** [comment]
I see it different.

I would like to create a todo by simply typing it in. By typing @<context> or +<project>, the tags will be added automatically to the corresponding field below.

**Comment by georgepapas123** [comment]
In that case, I see the usefulness.

**Comment by georgepapas123** [comment]
In that case, I see the usefulness.

**Comment by georgepapas123** [comment]
In that case, I see the usefulness.
