### ISSUE TITLE
Don't change context and project to lowercase

### ISSUE THREAD

**Issue by azzamsa** [tmaegel/ntodotxt#64]
Hi, 👋🏽 

I am using [Sleek](https://github.com/ransome1/sleek) on my Desktop and ntodotxt on mobile.
But ntodotxt changed all my project and context to lowercase, which I don't want.
As the [spec](https://github.com/todotxt/todo.txt?tab=readme-ov-file#incomplete-tasks-3-format-rules) also don't have this limitation, and we are free to use any capitalization in the context.

Thanks! 🥞

**Comment by Mrnofish** [comment]
Seconded, forcing lowercase basically involves the use of underscores for legibility, whereas with capitalization it could be maintained with fewer letters and less typing.
