### ISSUE TITLE
Open todo.txt from file system when choosing offline

### ISSUE THREAD

**Issue by mshuflin** [tmaegel/ntodotxt#7]
When choosing "offline", there does not seem to be a way to open an existing todo.txt file. Is it possible to read and write to a local todo.txt file, allowing ntodotxt to be used alongside other apps as well for syncing with syncthing?

**Comment by tmaegel** [comment]
Configuring a custom path is already on my roadmap. Importing an existing file sounds like a useful feature.

**Comment by tmaegel** [comment]
Feature was added with the following commit 3bd15151952212c4ba883697f7bfdb17e1ee1513
