### ISSUE TITLE
WebDAV with self-signed certificate

### ISSUE THREAD

**Issue by azzamsa** [tmaegel/ntodotxt#72]
Hi,

I am setting up my own WebDAV using [mholt/caddy-webdav: WebDAV handler module for Caddy](https://github.com/mholt/caddy-webdav). And it doesn't have any base URL, as I am using a subdomain for this. But the `BASE_URL` in the app initial setup is mandatory, putting `/` doesn't work.

Thanks.

**Comment by tmaegel** [comment]
Are you using a self-signed certificate? Because there is still a known problem with this?

**Comment by azzamsa** [comment]
> Are you using a self-signed certificate? Because there is still a known issue with this?

I belive Yes. As I am using Caddy to manage the certificates.

**Comment by tmaegel** [comment]
Okay then I think this is the reason for the issue. I'll try to fix this with the next release.I have the same problem with my self-hosted/self-signed setup.
